listen_addresses = ['127.0.0.1:53','[::1]:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
fallback_resolver = '185.228.168.10:53'
ignore_system_dns = false
netprobe_timeout = 60
netprobe_address = '185.228.168.10:53'
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = true
reject_ttl = 600
cache = true
cache_size = 1024
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
disabled_server_names = []
[query_log]
  format = 'ltsv'

[nx_log]
  format = 'ltsv'

[blacklist]

[ip_blacklist]

[sources]

[static]
